version: '3.8'

services:
  nodeapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: university-nodeapp  # Explicit image name
    container_name: university-nodeapp  # Explicit container name
    ports:
      - "4000:4000"
    networks:
      - university-app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://localhost:27017/university
      PORT: 3000
      JWT_SECRET: your_jwt_secret

networks:
  university-app:
    external: true