version: '3.8'

services:
  nodeapp:
    build: 
      context: .
      dockerfile: Dockerfile
    image: university-nodeapp  # Explicit image name
    container_name: university-nodeapp  # Explicit container name
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/university
    networks:
      - university-app

networks:
  university-app:
    external: true