apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: NodePort  # You can change it to LoadBalancer if you're using a cloud provider
