version: '3.8'

services:
  # MongoDB
  mongo:
    image: mongo:5.0

    volumes:
      - mongo_data:/data/db
    networks:
      university-app

  # Mongo Express
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
       MONGO_URI: mongodb://mongo:27017/university
       ME_CONFIG_MONGODB_SERVER: mongo
       ME_CONFIG_MONGODB_PORT: 27017
       ME_CONFIG_BASICAUTH_USERNAME: admin
       ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongo
    networks:
      university-app

volumes:
  mongo_data:

networks:
  university-app: